name: Validate and test

on:
  pull_request:
  push:
    branches:
      - main
    tags-ignore: [ v.* ]

jobs:
  check-code-style:
    name: Checks
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # we don't know what commit the last tag was it's safer to get entire repo so previousStableVersion resolves
          fetch-depth: 0
      - name: Checkout GitHub merge
        if: github.event.pull_request
        run: |-
          git fetch origin pull/${{ github.event.pull_request.number }}/merge:scratch
          git checkout scratch
      - name: Set up JDK 11
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.11.0-9
      - name: Cache Coursier cache
        uses: coursier/cache-action@v5
      - name: Code style check and binary-compatibility check
        run: |-
          cp .jvmopts-ci .jvmopts
          sbt scalafmtCheckAll scalafmtSbtCheck headerCheck

  compile-and-test:
    name: Compile and test
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Checkout GitHub merge
        if: github.event.pull_request
        run: |-
          git fetch origin pull/${{ github.event.pull_request.number }}/merge:scratch
          git checkout scratch

      - name: Set up JDK 11
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.11.0-9

      - name: Cache Coursier cache
        uses: coursier/cache-action@v5

      - name: Compile and test
        run: sbt test

  test-docs:
    name: Docs
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Checkout GitHub merge
        if: github.event.pull_request
        run: |-
          git fetch origin pull/${{ github.event.pull_request.number }}/merge:scratch
          git checkout scratch
      - name: Set up JDK 11
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.11.0-9
      - name: Cache Coursier cache
        uses: coursier/cache-action@v5
      - name: Test Maven Java
        run: |-
          cp .jvmopts-ci .jvmopts
          sbt docs/paradox

